#!/bin/bash

case $BLOCK_BUTTON in
  1) amixer -q sset Master toggle ;;  # left click, mute/unmute
  4) amixer -q sset Master 5%+ ;; # scroll up, increase
  5) amixer -q sset Master 5%- ;; # scroll down, decrease
esac

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $4}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  if [[ "${volume}" -eq "100" ]]; then
    echo "${volume}%"
    echo "${volume}%"
    echo ""
  elif [[ "${volume}" -ge "10" ]]; then
    echo " ${volume}%"
    echo " ${volume}%"
    echo ""
  else
    echo "  ${volume}%"
    echo "  ${volume}%"
    echo ""
  fi
else
  echo "mute"
  echo "mute"
  echo ""
fi