#!/bin/bash

BATTERY_INFO=$(acpi -b | grep "Battery 0")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
TIME=$(echo "${BATTERY_INFO}" | sed -n 's/.*[0-9]\([0-9]:[0-9][0-9]\):[0-9][0-9].*/\1/p')
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

# show a big warning if battery power is low
if [[ ${BATTERY_POWER} < 20 && "${BATTERY_STATE}" = "Discharging" ]]; then
  pgrep i3-nagbar >& /dev/null
  if [[ $? != 0 ]]; then
    MESSAGE="Low Battery: ${BATTERY_POWER}% remaining"
    DISPLAY=:0.0 i3-nagbar -m "$(echo $MESSAGE)" -b  'Shutdown' 'systemctl poweroff' -b 'Hybrid-Sleep' 'systemctl hybrid-sleep' -b 'Suspend' 'systemctl suspend' >& /dev/null &
  fi
fi

if [[ "${BATTERY_INFO}" = "" ]]; then
  echo "---"
  echo "---"
  echo ""
elif [[ "${BATTERY_STATE}" = "Charging" && "${TIME}" != "" ]]; then
  echo "+${TIME}"
  echo "+${TIME}"
  echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" && "${TIME}" != "" ]]; then
  echo " -${TIME}"
  echo " -${TIME}"
  echo ""
else
  echo "  ${BATTERY_POWER}%"
  echo "  ${BATTERY_POWER}%"
  echo ""
fi
