#!/bin/bash

BATTERY_INFO=$(acpi -b | grep "Battery 0")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
TIME=$(echo "${BATTERY_INFO}" | sed -n 's/.*[0-9]\([0-9]:[0-9][0-9]\):[0-9][0-9].*/\1/p')

if [[ "${BATTERY_INFO}" = "" ]]; then
  echo "---"
  echo "---"
  echo ""
elif [[ "${BATTERY_STATE}" = "Charging" && "${TIME}" != "" ]]; then
  echo "+${TIME}"
  echo "+${TIME}"
  echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" && "${TIME}" != "" ]]; then
  echo " -${TIME}"
  echo " -${TIME}"
  echo ""
else
  BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
  echo "  ${BATTERY_POWER}%"
  echo "  ${BATTERY_POWER}%"
  echo ""
fi