#!/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  connman-gtk &
fi

wired_device=$(echo "${BLOCK_INSTANCE}" | awk -F ';' '{print $1}')
wireless_device=$(echo "${BLOCK_INSTANCE}" | awk -F ';' '{print $2}')

wired_status=$(cat /sys/class/net/${wired_device}/operstate)
wireless_status=$(cat /sys/class/net/${wireless_device}/operstate)

if [[ "${wired_status}" == "up" ]]; then
  echo "   wired"
  echo "   wired"
  echo ""
elif [[ "${wireless_status}" == "up" ]]; then
  quality=$(grep ${wireless_device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
  echo "  ${quality}%"
  echo "  ${quality}%"
  echo ""
else
  echo "  ---"
  echo "  0%"
  echo ""
fi